<?php
require(dirname(__DIR__)."/PHPriotAPI/champion.php");
require(dirname(__DIR__)."/PHPriotAPI/current-game.php");
require(dirname(__DIR__)."/PHPriotAPI/featured-games.php");
require(dirname(__DIR__)."/PHPriotAPI/game.php");
require(dirname(__DIR__)."/PHPriotAPI/leagues.php");
require(dirname(__DIR__)."/PHPriotAPI/lol-static-data.php");
require(dirname(__DIR__)."/PHPriotAPI/lol-status.php");
require(dirname(__DIR__)."/PHPriotAPI/match.php");
require(dirname(__DIR__)."/PHPriotAPI/matchhistory.php");
require(dirname(__DIR__)."/PHPriotAPI/stats.php");
require(dirname(__DIR__)."/PHPriotAPI/summoner.php");
require(dirname(__DIR__)."/PHPriotAPI/team.php");
?>
